### ISSUE TITLE
Keybinds don't update on login

### ISSUE THREAD

**Issue by zasrin** [myzb/SpecSpecificKeybinds#2]
My keybinds are updating fine when I change specs but when I change characters my keybinds do not update. Please make the keybinds load on login/char load.

**Comment by myzb** [comment]
By not updating do you mean that there is no message saying "Key bindings set to specialization: XYZ" ? when you log in?

This is because if you for example log out in spec "Shadow" and log back in again, there will be no need to reload the keybinds since you are still in the same spec. Therefore the message won't be printed. I aware this can be confusing, since things like the message about "loot specialization changed" is always shown when you log in.

**Comment by zasrin** [comment]
My Prot Pally spec has very different keybinds compared to my rogue's specs. When i switch specs on my pally the keybinds change around just fine. When I log off in prot and then log into my rogue my keybinds do not update to my rogue's keybinds. They stay as the keybinds of my prot pally until I change the spec of my rogue, at which point my keybinds change just fine.

**Comment by myzb** [comment]
I think I know what's going on. Can you check if the default in-game keybinding menu has the checkbox for "character specific keybinds" set? I may have forgotten to account for the possibility of that checkbox being used.

The option should be somewhere near the top of the window.

**Comment by zasrin** [comment]
Yes that option is checked. Should I disable this? Or will the addon be updated to work with that enabled?

**Comment by myzb** [comment]
I just updated the addon. You can get it from here: https://github.com/myzb/SpecSpecificKeybinds/releases/download/0.8-beta/SpecSpecificKeybinds-0.8-beta.zip 

or through the curse client once it get synced.

**Comment by zasrin** [comment]
Thanks confirmed fixed.
